### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by brettz9** [devongovett/unicode-trie#1]
Might you be able to build this package in such a way as to allow browser support? I know Unicode info may be large, but I have a use for caching such scripts client-side....

**Comment by devongovett** [comment]
Generally you won't want to build tries in the browser, but you may want to use them there.

You can use [browserify](http://github.com/substack/node-browserify) to build for the browser, and it works just fine. You'll need to inline the generated trie data, using [brfs](https://github.com/substack/brfs). For an example, see [linebreak](https://github.com/devongovett/linebreak) and [grapheme-breaker](https://github.com/devongovett/grapheme-breaker) which both use `unicode-trie` under the hood, and work in the browser via browserify.

**Comment by brettz9** [comment]
Awesome, thanks!
